version: 1.0
name: my-cicd
stages:
  git-clone:
    steps:
      - name: git-clone
        uses: git-checkout
        with:
          url: https://gitee.com/mohaijiang/spring-boot-example.git
          branch: master
  code-compile:
    needs:
      - git-clone
    steps:
      - name: code-compile
        runs-on: maven:3.5-jdk-8
        run: |
          mvn clean package -Dmaven.test.skip=true

